In [1]:
import pandas as pd
import numpy as np

In [2]:
# Q1 -> 2.3.1
pd.__version__

'2.3.1'

In [3]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-09-30 23:59:40--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.04s   

2025-09-30 23:59:40 (23.3 MB/s) - ‘car_fuel_efficiency.csv’ saved [874188/874188]



In [4]:
!ls

'Introduction to Numpy.ipynb'   homework_2024.ipynb   pandas.ipynb
 car_fuel_efficiency.csv        homework_2025.ipynb


In [5]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [6]:
df.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [7]:
# Q2 -> 9704
df.shape[0]

9704

In [8]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [9]:
# Q3  -> 2
df.fuel_type.nunique()

2

In [10]:
# Q4  ->  4
df.isnull().any().sum()

np.int64(4)

In [11]:
df.origin.unique()

array(['Europe', 'USA', 'Asia'], dtype=object)

In [12]:
# Q5 - > 23.75
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()


np.float64(23.759122836520497)

In [13]:
# Q6 -> Yes
df.horsepower.median()

np.float64(149.0)

In [14]:
# Q6
df.horsepower.mode()[0]

np.float64(152.0)

In [15]:
freq_horsepower = df.horsepower.mode()[0]
freq_horsepower

np.float64(152.0)

In [16]:
df.horsepower = df.horsepower.fillna(freq_horsepower)

In [17]:
df.horsepower.median()

np.float64(152.0)

In [18]:
# Q7 -> 0.51
asia_cols = df[df.origin == 'Asia'][['vehicle_weight', 'model_year']][:7]
asia_cols

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [19]:
X = np.array(asia_cols)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [20]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [21]:
y =  [1100, 1300, 800, 900, 1000, 1100, 1200]

In [22]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

In [23]:
w.sum().round(4)

np.float64(0.5188)